name: churn-batch-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas==2.1.4
      - numpy==1.26.4
      - scikit-learn==1.3.2
      - xgboost==2.0.3
      - joblib==1.3.2
      - pyarrow==14.0.1
      - azureml-core
      - azureml-dataset-runtime
